version: '3.2'

services:
  biobot:
    image: tg-time-bio-bot
    build: .
    container_name: tg-time-bio-bot
    restart: unless-stopped
    env_file:
      - env
    environment:
      - TIME_ZONE=Europe/Minsk
      - "BIO_PATTERN=my local time is {TIME}"
    volumes:
      - ./session:/app/session
